Docs update
architect-templates/node-rest-api pull request #10
Opened 2022-09-16 00:42 UTC by ryan-cahill

## Overview
Updated docs to deploy the component config file rather than the component by name

## Changes
* Doc updates related to deployments
* Fixed dead/bad links

## Pictures

![image](https://user-images.githubusercontent.com/8558567/190532298-d3336ee9-7932-4a48-81a4-87b05afe1643.png)

## TODO List
Before merging, a PR will need
- [ ] Signoff from @Zach-at-Arch for UX
- [ ] Signoff from one other engineer at Architect.io

2022-09-16 15:52 UTC, Zach-at-Arch commented on README.md
> +You can then [deploy the component](https://docs.architect.io/getting-started/introduction/#deploy-to-the-cloud) using the command below from the `node-rest-api` directory. "example-environment" is t
Change to (keep the hyperlinks):
You can then deploy the component by running the command below from the `node-rest-api` directory. Note that “example-environment” is the free environment that is created with your Architect account.

2022-09-16 15:53 UTC, Zach-at-Arch requested changes
Small wording change for clarity

2022-09-19 17:20 UTC, Zach-at-Arch approved these changes

2022-09-21 00:32 UTC, mtgoncalves1 approved these changes
Both local and remote deployments were successful on M1 machine.

2022-10-04 17:35 UTC, merged